"""
Nathan: added setup.py so that can 'pip install -e .'
"""
from setuptools import setup, find_packages

setup(
    name="lerobot",
    version="0.1.0",
    description="🤗 LeRobot: State-of-the-art Machine Learning for Real-World Robotics in Pytorch",
    author="Rémi Cadène, Simon Alibert, Alexander Soare, Quentin Gallouédec, Adil Zouitine, Thomas Wolf",
    author_email="re.cadene@gmail.com, alibert.sim@gmail.com, alexander.soare159@gmail.com, quentin.gallouedec@ec-lyon.fr, adilzouitinegm@gmail.com, thomaswolfcontact@gmail.com",
    url="https://github.com/huggingface/lerobot",
    license="Apache-2.0",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Intended Audience :: Education",
        "Intended Audience :: Science/Research",
        "Topic :: Software Development :: Build Tools",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "License :: OSI Approved :: Apache Software License",
        "Programming Language :: Python :: 3.10",
    ],
    packages=find_packages(include=["lerobot"]),
    python_requires=">=3.10,<3.13",
    install_requires=[
        "termcolor>=2.4.0",
        "omegaconf>=2.3.0",
        "wandb>=0.16.3",
        "imageio[ffmpeg]>=2.34.0",
        "gdown>=5.1.0",
        "hydra-core>=1.3.2",
        "einops>=0.8.0",
        "pymunk>=6.6.0",
        "zarr>=2.17.0",
        "numba>=0.59.0",
        "torch>=2.2.1",
        "opencv-python>=4.9.0",
        "diffusers>=0.27.2",
        "torchvision>=0.17.1",
        "h5py>=3.10.0",
        "huggingface-hub[hf-transfer]>=0.23.0",
        "gymnasium>=0.29.1",
        "cmake>=3.29.0.1",
        "datasets>=2.19.0",
        "pyav>=12.0.5",
        "moviepy>=1.0.3",
        "rerun-sdk>=0.15.1",
        "deepdiff>=7.0.1",
    ],
    extras_require={
        "dora": ["gym-dora @ git+https://github.com/dora-rs/dora-lerobot.git@master#subdirectory=gym_dora"],
        "pusht": ["gym-pusht>=0.1.3"],
        "xarm": ["gym-xarm>=0.1.1"],
        "aloha": ["gym-aloha>=0.1.1"],
        "dev": ["pre-commit>=3.7.0", "debugpy>=1.8.1"],
        "test": ["pytest>=8.1.0", "pytest-cov>=5.0.0"],
        "umi": ["imagecodecs>=2024.1.1"],
    },
    include_package_data=True,
    zip_safe=False,
)
