# @package _global_

fps: 10

env:
  name: maze
  task: maze
  image_size: 96
  state_dim: 2
  action_dim: 2
  fps: ${fps}
  episode_length: 104
  gym:
    obs_type: pixels_agent_pos
    render_mode: rgb_array
    # visualization_width: 384
    # visualization_height: 384

